version: '3.7'
services:
    elasticsearch:
       image: elasticsearch:7.4.2
       env_file: .env
       ports:
         - "9200:9200"
         - "9300:9300"
    logstash:
       image: logstash:7.4.2
       env_file: .env
       ports:
         - "5044:5044"
    #      - "9300:9300"
    kibana:
       image: kibana:7.4.2
       env_file: .env
       ports:
         - "5601:5601"

